name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend:
    name: Backend (.NET 9) build & test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      ASPNETCORE_ENVIRONMENT: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true

      - name: Restore
        run: dotnet restore Backend.csproj

      - name: Build (Release)
        run: dotnet build Backend.csproj --configuration Release --no-restore

      - name: Test (Release)
        run: dotnet test Backend.csproj --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: Backend/TestResults

  frontend:
    name: Frontend (Node) build, lint & test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Unit tests
        env:
          CI: 'true'
        run: npm run test

      - name: Upload frontend build (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
